[tool.black]
line-length = 100
target-version = ['py311']

[tool.ruff]
select = ["E", "F", "UP", "B", "I", "PGH", "PL", "RUF"]
line-length = 100
target-version = "py311"
ignore = ["PLR2004", "PLR0913", "PLR0912", "PLW2901", "PLR0915"]
